### ISSUE TITLE
Requesting Attachments of Documents 

### ISSUE THREAD

**Issue by PoornaSiva** [Dhanupoorna/WhatsUp_Development#4]
Dear Dhanupoorna, 

it would be great if the app is capable of attaching the documents as well. Kindly add this feature

**Comment by Dhanupoorna** [comment]
Dear poorna thanks for suggesting this feature .we will add let you know

**Comment by Dhanupoorna** [comment]
Dear poorna , Thanks for your valuable suggestions .this feature is going to make our product great.
